import { chromium } from 'playwright';
import assert from 'node:assert/strict';
import { mkdtemp, cp, readFile, writeFile, rm, mkdir } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { Source, loadConfig } from '../src/source.js';
import { startServer } from '../src/server.js';
const root = await mkdtemp(path.join(os.tmpdir(), 'current-board-'));
await cp('examples/synthetic', root, {recursive:true});
const file = path.join(root,'graph.json'), g = JSON.parse(await readFile(file,'utf8'));
g.nodes.find(n=>n.id==='INGEST').status='in_progress';
g.nodes.find(n=>n.id==='INGEST').checkpoint={status:'partial_content_preparation',summary:'First batch checked <img src=x onerror=alert(1)>; review pending'};
g.views=g.views.filter(v=>v.mode!=='all');
g.journeys=[{id:'FLOW',title:'Import flow',outcome:'Import and read',boundaries:'Import retry',itemIds:['INGEST'],acceptanceCriteria:[],recordSource:'explicit'}];
await writeFile(file,JSON.stringify(g));
const server=await startServer(new Source(await loadConfig(path.join(root,'config.json'))),0);
const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});
const page=await browser.newPage({viewport:{width:1440,height:1100}});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
const refresh=async()=>{await writeFile(file,JSON.stringify(g));await page.locator('#refresh').click();};
try {
 await page.goto(server.url);
 await page.locator('#current-tasks button').waitFor();
 assert.ok(await page.evaluate(()=>document.getElementById('cy')._cyreg.cy.zoom()) >= .9);
 assert.equal(await page.locator('#minimap svg').count(),1);
 assert.equal(await page.evaluate(()=>document.getElementById('cy')._cyreg.cy.getElementById('ARCHIVE-SPEC').data('progressState')),'complete');
 assert.equal(await page.evaluate(()=>document.getElementById('cy')._cyreg.cy.getElementById('group:launch').data('progressState')),'partial');
 assert.match(await page.evaluate(()=>document.getElementById('cy')._cyreg.cy.getElementById('group:launch').data('label')),/已完成 1\/4/);
 const pan=await page.evaluate(()=>document.getElementById('cy')._cyreg.cy.pan());
 await page.locator('#minimap svg').focus(); await page.keyboard.press('ArrowRight');
 assert.notDeepEqual(await page.evaluate(()=>document.getElementById('cy')._cyreg.cy.pan()),pan);
 await page.keyboard.press('ArrowLeft');
 assert.match(await page.locator('#counts').innerText(),/10 \/ 10/);
 assert.match(await page.locator('#current-position').innerText(),/Archive foundation/);
 assert.equal(await page.locator('#current-checkpoint').count(),1,'Current checkpoint must be visible without opening raw details');
 assert.equal(await page.locator('#current-checkpoint').isVisible(),true);
 assert.match(await page.locator('#current-checkpoint').innerText(),/First batch checked <img/);
 assert.equal(await page.locator('#current-checkpoint img').count(),0,'Checkpoint text must not become HTML');
 g.nodes.find(n=>n.id==='INGEST').checkpoint.summary='Second batch checked; final review still pending';await refresh();
 await page.waitForFunction(()=>document.getElementById('current-checkpoint').textContent.includes('Second batch'));

 await page.locator('#current-more summary').click();
 assert.match(await page.locator('#current-context').innerText(),/Archive foundation/);
 await page.locator('#current-more summary').click();
 assert.equal(await page.evaluate(()=>document.getElementById('cy')._cyreg.cy.nodes('[active]').length),1);
 await page.locator('#search').fill('ARCHIVE-SPEC');await page.locator('#search').press('Enter');
 assert.match(await page.locator('#current-tasks').innerText(),/INGEST/);
 assert.equal(await page.evaluate(()=>document.getElementById('cy')._cyreg.cy.nodes('[active]').length),1);
 await page.locator('#groups button').filter({hasText:'Archive foundation'}).click();
 assert.equal(await page.evaluate(()=>document.getElementById('cy')._cyreg.cy.nodes('[activeGroup]').length),1);
 await page.locator('#locate-current').click();
 assert.equal(await page.evaluate(()=>document.getElementById('cy')._cyreg.cy.nodes(':selected').data('originalId')),'INGEST');
 assert.match(await page.locator('#detail .checkpoint-summary').innerText(),/Second batch/);
 assert.match(await page.locator('#detail').innerText(),/未知 \/ 未记录/,'Partial checkpoint must not imply whole-task verification');
 await page.locator('#views button').last().click();await page.locator('#locate-current').click();
 assert.match(await page.locator('#counts').innerText(),/10 \/ 10/);
 g.nodes.find(n=>n.id==='GUIDE').status='in_progress';await refresh();
 await page.waitForFunction(()=>document.querySelectorAll('#current-tasks button').length===2);
 assert.equal(await page.evaluate(()=>document.getElementById('cy')._cyreg.cy.nodes(':selected').data('originalId')),'INGEST');
 await page.locator('#current-tasks button').filter({hasText:'GUIDE'}).click();await page.locator('#locate-current').click();
 assert.equal(await page.evaluate(()=>document.getElementById('cy')._cyreg.cy.nodes(':selected').data('originalId')),'GUIDE');
 assert.match(await page.locator('#current-checkpoint').innerText(),/检查点未记录/);
 await page.locator('#current-tasks button').filter({hasText:'INGEST'}).click();
 await page.locator('#journey-select').selectOption('FLOW');
 await page.locator('#node-list button').filter({hasText:'INGEST'}).click();
 await page.locator('#roadmap-overview').click();
 assert.equal(await page.locator('#detail button').filter({hasText:'返回闭环验收'}).count(),0);
 await mkdir('local/evidence/current-work',{recursive:true});
 await page.screenshot({path:'local/evidence/current-work/multiple.png',fullPage:true});
 await page.setViewportSize({width:390,height:844});
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 await page.screenshot({path:'local/evidence/current-work/narrow.png',fullPage:true});
 await writeFile(file,'{');await page.locator('#refresh').click();
 await page.waitForFunction(()=>document.getElementById('current-note').textContent.includes('已过期'));
 assert.equal(await page.locator('#current-tasks button').count(),2);
 assert.match(await page.locator('#current-checkpoint').innerText(),/Second batch/,'Stale snapshot retains last known checkpoint');
 g.nodes.filter(n=>n.status==='in_progress').forEach(n=>n.status='accepted');await refresh();
 await page.waitForFunction(()=>document.getElementById('locate-current').disabled);
 assert.match(await page.locator('#current-note').innerText(),/没有记录/);
 assert.equal(await page.locator('#current-tasks button').count(),0);
 assert.equal(await page.locator('#current-checkpoint').isVisible(),false);
 assert.deepEqual(errors,[]);
 console.log('Current-work browser acceptance passed');
} finally { await browser.close(); await server.close(); await rm(root,{recursive:true,force:true}); }
