import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import {mkdtemp,cp,readFile,writeFile,rm} from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import {Source,loadConfig} from '../src/source.js';
import {startServer} from '../src/server.js';
const root=await mkdtemp(path.join(os.tmpdir(),'board-evolution-'));
await cp('examples/synthetic',root,{recursive:true});
const file=path.join(root,'graph.json'),g=JSON.parse(await readFile(file,'utf8'));
const server=await startServer(new Source(await loadConfig(path.join(root,'config.json'))),0);
const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});
try {
 const p=await browser.newPage({viewport:{width:1440,height:1000}});p.setDefaultTimeout(5000);
 await p.goto(server.url);await p.locator('#minimap svg').waitFor();
 const initial=await p.evaluate(()=>fetch('/api/snapshot').then(r=>r.json()));
 await p.locator('#search').fill('SEARCH');await p.locator('#search').press('Enter');
 await p.getByRole('button',{name:'聚焦这条依赖链',exact:true}).click();
 g.groups.push({id:'feedback',title:'Feedback loop'});
 const added={...structuredClone(g.nodes.find(n=>n.id==='GUIDE')),id:'FEEDBACK',title:'Capture visitor feedback',groupId:'feedback',status:'in_progress',dependsOn:['ARCHIVE-SPEC']};
 g.nodes=g.nodes.filter(n=>n.id!=='SEARCH');g.nodes.push(added);
 g.nodes.forEach(n=>{n.dependsOn=n.dependsOn.filter(id=>id!=='SEARCH');if(n.children)n.children=n.children.filter(id=>id!=='SEARCH');});
 g.nodes.find(n=>n.id==='EXHIBIT').dependsOn.push('FEEDBACK');
 g.views.forEach(v=>{if(v.nodeIds)v.nodeIds=v.nodeIds.filter(id=>id!=='SEARCH');});
 g.journeys=[{id:'NEW-FLOW',title:'Visitor feedback',outcome:'Collect feedback',boundaries:'Retry safely',recordSource:'explicit',itemIds:['FEEDBACK','EXHIBIT'],acceptanceCriteria:[]}];
 await writeFile(file,JSON.stringify(g));await p.locator('#refresh').click();
 await p.waitForFunction(()=>document.getElementById('current-tasks').textContent.includes('FEEDBACK'));
 assert.match(await p.locator('#detail').innerText(),/已从来源移除/);
 assert.equal(await p.locator('#clear-focus').isVisible(),false);
 assert.equal(await p.evaluate(()=>document.getElementById('cy')._cyreg.cy.nodes('.dim').length),0);
 assert.match(await p.locator('#groups').innerText(),/Feedback loop/);
 await p.locator('#journey-select').selectOption('NEW-FLOW');
 assert.match(await p.locator('#journey-summary').innerText(),/1/);
 const latest=await p.evaluate(()=>fetch('/api/snapshot').then(r=>r.json()));
 assert.notEqual(latest.freshness.hash,initial.freshness.hash);
 assert.ok(!latest.graph.nodes.some(n=>n.id==='SEARCH'));
 assert.ok(latest.graph.nodes.find(n=>n.id==='EXHIBIT').dependsOn.includes('FEEDBACK'));
 g.nodes.find(n=>n.id==='ARCHIVE-SPEC').dependsOn=['FEEDBACK'];
 await writeFile(file,JSON.stringify(g));await p.locator('#refresh').click();
 await p.waitForFunction(()=>document.getElementById('alert').textContent.includes('STALE'));
 assert.match(await p.locator('#current-tasks').innerText(),/FEEDBACK/);
 console.log('Evolution acceptance passed: live source add/remove/regroup/rewire/new journey; invalid cycle retains explicitly stale snapshot.');
}finally {await browser.close();await server.close();await rm(root,{recursive:true,force:true});}
